### ISSUE TITLE
Why are softplus and logsigmoid implemented independently?

### ISSUE THREAD

**Issue by Sleort** [FluxML/NNlib.jl#102]
It is easy to show that `softplus(x) == -logσ(-x)`, so I'm curious about why these functions are defined independently in activation.jl. Is there a reason for this? Wouldn't it be easier to implement/maintain just one of them and use the above relation for the other?

(I did a quick benchmark on my laptop to see which one is the faster. Although I couldn't determine a clear winner, the `softplus` version seems to be numerically more stable. E.g.,
```
julia> logσ(40)
-0.0

julia> -softplus(-40)
-4.248354255291589e-18
```
)

**Comment by MikeInnes** [comment]
Probably only historical (i.e. someone implemented one without realising the other was there already). It'd be fine to rewrite things to share the implementation. There may be some advantage in keeping both names, though, if it makes it easier to look for when people don't know this relationship.

**Comment by Sleort** [comment]
I see. I did a slightly more detailed benchmark on my laptop, comparing the current implementations of `logσ` and `softplus`:
```
julia> using NNlib, BenchmarkTools, Plots

julia> r_F32 = range(-10.0f0,10.0f0,length=41)
-10.0f0:0.5f0:10.0f0

julia> r_F64 = range(-10.0,10.0,length=41)
-10.0:0.5:10.0

julia> bm_logσ_32 = [@belapsed(logσ($x)) for x ∈ r_F32];

julia> bm_softplus_32 = [@belapsed(softplus($x)) for x ∈ r_F32];

julia> bm_logσ_64 = [@belapsed(logσ($x)) for x ∈ r_F64];

julia> bm_softplus_64 = [@belapsed(softplus($x)) for x ∈ r_F64];

julia> plot(r_F32,[bm_logσ_32,bm_softplus_32], marker = 2, xlabel="x", ylabel="@belapsed",label=["f = logsigmoid", "f = softplus"], title="Float32 performance of f(x)")

julia> plot(r_F64,[bm_logσ_64,bm_softplus_64], marker = 2, xlabel="x", ylabel="@belapsed",label=["f = logsigmoid", "f = softplus"], title="Float64 performance of f(x)")
```
and got
[F32_benchmark.pdf](https://github.com/FluxML/NNlib.jl/files/3036497/F32_benchmark.pdf)
[F64_benchmark.pdf](https://github.com/FluxML/NNlib.jl/files/3036498/F64_benchmark.pdf)
So if my computer/benchmarking is representative, it seems that the current `softplus` implementation is slightly better (order of 10%) in the most important region (around 0). This, together with `softplus`'s better numerical stability, means that I'd say `logσ` should be rewritten `logσ(x) = -softplus(-x)`... (I can do it if you want/agree)

**Comment by MikeInnes** [comment]
I'm on board :+1:
