### ISSUE TITLE
Convolution for mixed-precision inputs

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/NNlib.jl#107]
Currently it's easy to get errors due to passing (say) an f32 filter and f64 input to a convolution. We should make this a bit more liberal, either by loosening any unecessary type restrictions (some of the implementations are pure julia and this should work) or by just promoting the arrays to a common type.

**Comment by staticfloat** [comment]
I believe this is fixed now on `NNlib#master`; can you test?  Ideally I'd like to raise warnings when we fall back to a slow implementation, giving the user the ability to directly convert when they need to.

**Comment by MikeInnes** [comment]
Right you are. If performance is an issue we can figure that out separately.
