### ISSUE TITLE
Add maxpool and meanpool methods

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/NNlib.jl#120]
During the overhaul we lost `maxpool(x, (2, 2))` and co. This was not ideal as they are commonly used by users and, I think, expose a good simple API for doing pooling. We should add these convenience methods back.

**Comment by thebhatman** [comment]
@MikeInnes I have added methods for maxpool and meanpool so that they can be called simply as maxpool(x, (2,2)) and so on. https://github.com/FluxML/NNlib.jl/pull/121.

**Comment by CarloLucibello** [comment]
this can be closed
