### ISSUE TITLE
Include Knet in LICENSE file

### ISSUE THREAD

**Issue by oxinabox** [FluxML/NNlib.jl#14]
Acording to a comment at the top of:
https://github.com/FluxML/NNlib.jl/blob/1794fbbb51a06b0e6f21b8b53c066ae4535ec2ca/src/conv.jl#L2-L3

that code comes originally from KNet.jl
I believe by the terms of the MIT license (of KNet), NNlib.jl needs to acknowledge that in a particular way.
Normally I believe that this is done in the LICENSE.md file.

**Comment by MikeInnes** [comment]
Our CPU convolutions were recently rewritten from scratch, so I don't think this is an issue any more.
