### ISSUE TITLE
Fails on loading NNlib/udnNA/deps/deps.jl

### ISSUE THREAD

**Issue by thortom** [FluxML/NNlib.jl#157]
NNlib fails on loading. What I am encountering is the following:

`using NNlib`
> ┌ Info: Precompiling NNlib [872c559c-99b0-510c-b3b7-b6c96a88d5cd]
> └ @ Base loading.jl:1273
> ERROR: LoadError: could not open file /home/thor/.julia/packages/NNlib/udnNA/deps/deps.jl
> Stacktrace:
>  [1] include at ./boot.jl:328 [inlined]
>  [2] include_relative(::Module, ::String) at ./loading.jl:1105
>  [3] include at ./Base.jl:31 [inlined]
>  [4] include(::String) at /home/thor/.julia/packages/NNlib/udnNA/src/NNlib.jl:1
>  [5] top-level scope at /home/thor/.julia/packages/NNlib/udnNA/src/NNlib.jl:8
>  [6] include at ./boot.jl:328 [inlined]
>  [7] include_relative(::Module, ::String) at ./loading.jl:1105
>  [8] include(::Module, ::String) at ./Base.jl:31
>  [9] top-level scope at none:2
>  [10] eval at ./boot.jl:330 [inlined]
>  [11] eval(::Expr) at ./client.jl:425
>  [12] top-level scope at ./none:3
> in expression starting at /home/thor/.julia/packages/NNlib/udnNA/src/NNlib.jl:8
> Failed to precompile NNlib [872c559c-99b0-510c-b3b7-b6c96a88d5cd] to /home/thor/.julia/compiled/v1.3/NNlib/A7zdE_porR5.ji.
> 
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
>  [3] _require(::Base.PkgId) at ./loading.jl:1024
>  [4] require(::Base.PkgId) at ./loading.jl:922
>  [5] require(::Module, ::Symbol) at ./loading.jl:917
>  [6] top-level scope at In[15]:1
> 

This occurs after a seemingly successful installation

`]add NNlib`
> Updating registry at `~/.julia/registries/General`
>   Updating git-repo `https://github.com/JuliaRegistries/General.git`
>  Resolving package versions...
>   Updating `~/.julia/environments/v1.3/Project.toml`
>   [872c559c] + NNlib v0.6.2
>   Updating `~/.julia/environments/v1.3/Manifest.toml`
>  [no changes]

When I run

`]add NNlib#ap/builderror`
> Updating git-repo `https://github.com/FluxML/NNlib.jl.git`
>  Resolving package versions...
>   Updating `~/.julia/environments/v1.3/Project.toml`
>   [872c559c] ↓ NNlib v0.6.2 ⇒ v0.6.0 #ap/builderror (https://github.com/FluxML/NNlib.jl.git)
>   Updating `~/.julia/environments/v1.3/Manifest.toml`
>   [872c559c] ↓ NNlib v0.6.2 ⇒ v0.6.0 #ap/builderror (https://github.com/FluxML/NNlib.jl.git)
>   [a759f4b9] + TimerOutputs v0.5.3

I have Julia version 1.3.0 and I am running this on Ubuntu 18.04 64-bit

**Comment by thortom** [comment]
I reinstalled Julia, now Julia 1.3.1, and there was no issue after that reistallation.
Thus I am closing this issue as not reproducible.

**Comment by moesphere** [comment]
I had the same issue. Reason is that it tries to open the `deps.jl` file although it does not exist if the package was first installed some time ago. Rebuilding the package solves the issue.

**Comment by misticorion** [comment]
I face the same issue, would you mind telling me how to rebuild NNlib?
I have Julia 1.3.0.

**Comment by chu-** [comment]
> I face the same issue, would you mind telling me how to rebuild NNlib?
> I have Julia 1.3.0.

`] build`

**Comment by MacKenzieHnC** [comment]
> I had the same issue. Reason is that it tries to open the `deps.jl` file although it does not exist if the package was first installed some time ago. Rebuilding the package solves the issue.

I can confirm that I have the right file in the right location, but I still receive this error. Reinstalling or rebuilding registries does not help.
