### ISSUE TITLE
Provide artifact for BB download

### ISSUE THREAD

**Issue by ViralBShah** [FluxML/NNlib.jl#192]
This is one of the few packages that does not yet have an artifact for BB download as noted in https://github.com/JuliaPackaging/Yggdrasil/issues/653

**Comment by aviks** [comment]
there is already a jll for NNPack. It just needs to be enabled for this package (and tagged with a minimum julia version of 1.3)

https://github.com/JuliaBinaryWrappers/NNPACK_jll.jl

**Comment by ViralBShah** [comment]
@dhairyagandhi96
