### ISSUE TITLE
Conv with batch dim adds channels

### ISSUE THREAD

**Issue by baggepinnen** [FluxML/NNlib.jl#217]
Consider the following 1D convolution of `x`, where a batch contains 2 signals. When performing the convolution, there's an extra channel added
```julia
using NNlib

x = randn(10,1,1,2)
y = x[:,:,:,1:1]
z = x[:,:,:,2:2]

ox = NNlib.conv(x,x, pad=(3,0,0,0))
oy = NNlib.conv(y,y, pad=(3,0,0,0))
oz = NNlib.conv(z,z, pad=(3,0,0,0))

# All of the following statements are true
ox[:,:,1:1,1:1] == oy # Expected
ox[:,:,1:1,2:2] ≈ ox[:,:,2:2,1:1] # Why does this "cross term" exist?
ox[:,:,2:2,2:2] == oz # Expected to be in [:,:,1:1,2:2]
```
My question is, why is the second channel (in the third dimension) added?

Ping @ymtoo

**Comment by CarloLucibello** [comment]
I think the confusion stems from using the same array `x` both as an input and has a kernel
>My question is, why is the second channel (in the third dimension) added?

this is expected given the shape of the kernel x, specifying 2 output channels
