### ISSUE TITLE
Conv Fallback Warning Hindering Intentional Work (With FixedPointNumbers)

### ISSUE THREAD

**Issue by RocketRoss** [FluxML/NNlib.jl#232]
https://github.com/FluxML/NNlib.jl/blob/d524be7dc1a44c96793c0e9b420469204a85e9e7/src/conv.jl#L206

I'm testing various FixedPointNumber schemes with the intention of quantising an ANN, and the the Warning is printed with every convolution, slowing progress and blinding me to my other prints.

My request is that it warns just once. (I didn't find a built in way to do this, so I imagine a boolean would need to be referenced)

**Comment by CarloLucibello** [comment]
closed in #236
