### ISSUE TITLE
@eval

### ISSUE THREAD

**Issue by mloubout** [FluxML/NNlib.jl#263]
Hello

I guess this is more of a question than an issue, but any reason why everything is done through `@eval` in `conv.jl`. It makes it quite a pain to work with it (can't define `rrrule` or any new dispatched function).

**Comment by CarloLucibello** [comment]
why? we use eval loops to avoid typing essentially the same code multiple times, but it should be entirely equivalent to manually defining the functions

**Comment by mloubout** [comment]
Sorry, been digging into for few days. It seems like Zygote has some hard-coded derivatives for `conv` (0.6 doesn't but dependencies compact issues for now), though was weird that would work by hand.
Closing, thanks for the swift answer.
