### ISSUE TITLE
rrule for `pad_constant` fails when using (l1, r1, ..., ln, rn) padding

### ISSUE THREAD

**Issue by torfjelde** [FluxML/NNlib.jl#293]
## Problem
When executing the following snippet:

```julia
using Zygote, NNlib

upad, ∂upad = Zygote.pullback(u -> NNlib.pad_zeros(u, (0, 1, 0, 1)), u)
upad # <= everything looks correct
∂upad(ones(size(upad)))
```

```julia
MethodError: no method matching size_and_center(::Array{Float64,2}, ::Tuple{Tuple{Int64,Int64},Tuple{Int64,Int64}})
Closest candidates are:
  size_and_center(::Any, ::Tuple{Vararg{Int64,N}}) where N at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:157

Stacktrace:
 [1] (::NNlib.var"#pad_constant_pullback#263"{2,Colon,Array{Float64,2},NTuple{4,Int64}})(::Array{Float64,2}) at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:170
 [2] ZBack at /home/tor/.julia/packages/Zygote/KpME9/src/compiler/chainrules.jl:77 [inlined]
 [3] (::Zygote.var"#kw_zpullback#40"{NNlib.var"#pad_constant_pullback#263"{2,Colon,Array{Float64,2},NTuple{4,Int64}}})(::Array{Float64,2}) at /home/tor/.julia/packages/Zygote/KpME9/src/compiler/chainrules.jl:103
 [4] #pad_zeros#242 at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:10 [inlined]
 [5] pad_zeros at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:10 [inlined]
 [6] #65 at ./In[62]:1 [inlined]
 [7] (::Zygote.var"#41#42"{typeof(∂(#65))})(::Array{Float64,2}) at /home/tor/.julia/packages/Zygote/KpME9/src/compiler/interface.jl:40
 [8] top-level scope at In[64]:1
 [9] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```

Seems like the issue is the line https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L170 which calls `size_and_center` which doesn't support `NTuple{N, NTuple{2, Int}}` despite `gen_pad` seeming only returning those formats https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L128-L145?

## Solution
Seems like adding the following implementation of `size_and_center` should fix it:

```julia
function size_and_center(x, pad::NTuple{N,NTuple{2, Int}}) where N
  sz = ntuple(i -> pad[i][1] + pad[i][2], N) .+ size(x)
  center = broadcast((x,y) -> x .+ y, axes(x), ntuple(i -> pad[i][2], N))
  sz, center
end
```

I can make a PR if this seems reasonable.

**Comment by DhairyaLGandhi** [comment]
Thanks for pointing it out!

I would recommend wrapping `p` in `tuplejoin` here to do it

https://github.com/FluxML/NNlib.jl/blob/ab03c42a5a555d723238449287581648f16df3e0/src/padding.jl#L169

**Comment by DhairyaLGandhi** [comment]
Hopefully that should catch it

**Comment by torfjelde** [comment]
Ah, yeah that would be an easier fix. But do you have "internal representation" for the padding? Seems like it's moving between `NTuple{N, Int}` and `NTuple{N, Tuple{2, Int}}`. Would it maybe be preferable to internally only use one of these rather than switching between them, e.g. `gen_pad` returns the latter but `size_and_center` returns the former.

**Comment by DhairyaLGandhi** [comment]
We can definitely consider that, but the latter is an extended representation of the former, managing things like expanding the symmetric padding etc.

**Comment by torfjelde** [comment]
Oh, so it's not just  `(l1, r1, ..., ln, rn)` vs. `((l1, r1), ..., (ln, rn))`?

**Comment by DhairyaLGandhi** [comment]
It's actually something like `(p1,p2), dims = (1,2), N = 3` becomes `((p1, p1), (p2,p2), (0,0))` and friends as well. Personally I'd drop the notion of dims here altogether and have the explicit input

**Comment by torfjelde** [comment]
Ah okay, so I thought that "internally", e.g. what's passed to `size_and_center` was actually `(p1, p1, p2, p2, 0, 0)` and the `(p1,p2), dims = (1,2), N = 3` representation was only used as user-arguments and nothing more, i.e. it was "normalized" after the call to `pad_zeros` and `pad_constant`.

> Personally I'd drop the notion of dims here altogether and have the explicit input

You mean just using `((p1, p1), (p2,p2), (0,0))` everywhere? If so, 100% agree.

**Comment by DhairyaLGandhi** [comment]
Yeah, that's what I was thinking. You could also give it `(p1, p1, p2,p2, 0,0)`, both would actually be efficient, rather than mangling it with `dims`.

**Comment by torfjelde** [comment]
So there seems to a bit of redundancy going on. E.g. if I print the values passed to `pad_constant` here https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L149, `pad` is actually in the representation we want, e.g. `((p1, p1), (p2, p2), (0, 0))`. As a result, the `pad_zeros_tuple` which is called on the next line simply flattens this to `(p1, p1, p2, p2, 0, 0)`, then passing the flatten version to `size_and_center`.

So we could maybe just drop all these intermediate conversions if we introduce the `size_and_center` method I proposed above.

**Comment by DhairyaLGandhi** [comment]
Typically we want to reduce everything to the flat definition so we don't do any unnecessary iteration/ indexing/ copies at runtime.

**Comment by torfjelde** [comment]
> I'd prefer to not have multiple definitions of size_and_center if we can avoid it.

Exactly, so what I'm saying that we can replace the current one with the one for `((l1, r1), ..., (ln, rn))` format. At the moment, AFAIK, all `gen_pad` methods return this format with the exception of this particular impl: https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L125.

So if we remove that, all the paddings passed around internally will be of the form `((l1, r1), ..., (ln, rn))` rather than someitmes this and sometimes `(l1, r1, ..., ln, rn)`. This means that we only need one impl of `size_and_center`, we can remove a bunch of the current `tuplejoin` that are being used, e.g. https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L150 can be completely removed and thus also leaving `pad_zeros_tuple` completely redundant.

Tests just passed, so I'll make a PR and you can decide if bad or good :+1:

**Comment by DhairyaLGandhi** [comment]
Cool!
