### ISSUE TITLE
scatter!() on CuArrays now triggers scalar operations

### ISSUE THREAD

**Issue by dfdx** [FluxML/NNlib.jl#298]
MWE:
```julia
using NNlib   # v0.7.17
using CUDA

CUDA.allowscalar(false)

scatter!(+, cu(rand(5)), cu([2.0]), cu([1]))
# ==> ERROR: scalar getindex is disallowed
```
Note that this works in ScatterNNlib (destination slightly modified to conform to older API):

```julia
ScatterNNlib.scatter_add!(cu(rand(5, 1)), cu([2.0]), cu([1]))
# ==> ok
```
From the recent PRs I see that only the generic (i.e. CPU) version of `scatter!()` is implemented. Is the CUDA version implemented somewhere, planned or is explicitly unsupported? 

cc: @yuehhua

**Comment by ToucheSir** [comment]
https://github.com/FluxML/NNlib.jl/pull/296?

**Comment by yuehhua** [comment]
As you see, we are currently migrating functionality of ScatterNNlib.jl to NNlib.jl. `scatter!()` for generic use is merged, while for cuda is WIP. `scatter!()`, `scatter()`, `gather!()` and `gather()` will be supported for CPU and CUDA, as well as their AD in the future.

**Comment by dfdx** [comment]
Perfect, thank you!
