### ISSUE TITLE
`softmax` and `logsoftmax` fail (too silently) for integer arrays

### ISSUE THREAD

**Issue by Sleort** [FluxML/NNlib.jl#32]
Ideally, either
```
julia> using NNlib

julia> xs = rand(1:10,5)
5-element Array{Int64,1}:
 4
 8
 2
 8
 2

julia> softmax(xs)

Error thrown in threaded loop on thread 0: InexactError()5-element Array{Int64,1}:
               1
 140422637785272
 140422637830184
 140422637778824
              10

julia> logsoftmax(xs)

Error thrown in threaded loop on thread 0: InexactError()5-element Array{Int64,1}:
 140422640438016
 140422640438080
 140422657585728
 140422640435408
 140422195557936
```
should work (types being promoted etc.) properly. At a minimum, a "stronger error" that terminates the program execution should be thrown in this case. At the moment, it's still possible to continue program execution with the wrong results, e.g. `sum(softmax(xs))`, which is not good.

**Comment by MikeInnes** [comment]
Not perfect, but the type restriction will at least avoid obscure errors for now.
