### ISSUE TITLE
Consider using LogExpFunctions

### ISSUE THREAD

**Issue by cossio** [FluxML/NNlib.jl#331]
Consider using and re-exporting `logsumexp` from https://github.com/JuliaStats/LogExpFunctions.jl/blob/master/src/logsumexp.jl, instead of implementing it here (https://github.com/FluxML/NNlib.jl/blob/a3875e13148e2f8f61d5d4ef11a175f8020d5504/src/softmax.jl#L140).

Notice that the `LogExpFunctions` implementation is more sophisticated (maybe faster?) and works for arbitrary iterators (via a one-pass algorithm).

**Comment by mcabbott** [comment]
Xref #252

**Comment by CarloLucibello** [comment]
closing in favor of #252
