### ISSUE TITLE
`ForwardDiff` and `Conv`: Slow fallback implementation invoked for conv!

### ISSUE THREAD

**Issue by garibarba** [FluxML/NNlib.jl#349]
```julia
using Flux
using ForwardDiff

x = rand(Float32, 5, 5, 1, 1)
layer = Conv((3,3), 1 => 1, pad=(1, 1), stride=(1, 1))
f = x -> sum(layer(x))

ForwardDiff.gradient(f, x)
```
Outputs:
```
┌ Warning: Slow fallback implementation invoked for conv!  You probably don't want this; check your datatypes.
│   yT = ForwardDiff.Dual{ForwardDiff.Tag{var"#5#6", Float32}, Float32, 9}
│   T1 = ForwardDiff.Dual{ForwardDiff.Tag{var"#5#6", Float32}, Float32, 9}
│   T2 = Float32
└ @ NNlib ~/.julia/packages/NNlib/CSWJa/src/conv.jl:291
```
although the result is correct.

Does this mean there is a slowdown? Or not necessarily?

**Comment by garibarba** [comment]
Related to https://github.com/SciML/DiffEqSensitivity.jl/issues/473

**Comment by ToucheSir** [comment]
There is probably a slowdown, but I'm not sure you can do much better with dual numbers since the fast path requires BLAS-compatible data types.

**Comment by DhairyaLGandhi** [comment]
If ForwardDiff overloads the definition of `<op>(::AbstractArray{Dual}...)` it can take advantage of blas in cases where it makes sense.
