### ISSUE TITLE
(Flaky?) CI failures on GHA latest + Buildkite

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/NNlib.jl#359]
The Appveyor badge in the readme should be swapped out for a Buildkite one as well.

**Comment by DhairyaLGandhi** [comment]
Is it flaky or have many of the tests been consistently failing? GPU tests and some convolution tests come to mind.

**Comment by ToucheSir** [comment]
At least on the couple of commits I checked, different AD tests were failing between the different CI services. Which seems like a fun problem :sweat_smile:

**Comment by ToucheSir** [comment]
After some more digging, these failures really do seem random. I've yet to see all 3 conv spatial autodiff suites fail in one run, but it's not uncommon to see tests in 2/3 fail. Perhaps the tolerances are too strict?

**Comment by ToucheSir** [comment]
Does anyone know how many threads Buildkite runs by default? I had a look back through test failures on merge commits on GHA, and they are solely limited to the config with 2 threads (e.g. [1](https://github.com/FluxML/NNlib.jl/runs/3533818348?check_suite_focus=true), [2](https://github.com/FluxML/NNlib.jl/runs/4070591455?check_suite_focus=true), [3](https://github.com/FluxML/NNlib.jl/runs/3922909573?check_suite_focus=true)). My hunch is that Buildkite is using more threads by default and thus running into issues more frequently.

**Comment by ToucheSir** [comment]
Ok, I've been able to replicate this semi-frequently locally with 4/8 threads (on 4 cores). Running the depthwise conv fuzz tests is pretty damning:
```
[ Info: Starting Depthwise Convolutional fuzzing tests; this can take a few minutes...
.......................fuzzing: Test Failed at /home/brianc/projects/julia-dev/NNlib.jl/test/conv.jl:635
  Expression: dw_direct ≈ dw_im2col
   Evaluated: [0.18744640672662355] ≈ [0.00810922314783625]
Stacktrace:
 [1] macro expansion
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:635 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:565
fuzzing: Test Failed at /home/brianc/projects/julia-dev/NNlib.jl/test/conv.jl:635
  Expression: dw_direct ≈ dw_im2col
   Evaluated: [0.18744640672662355] ≈ [0.1856732181254305]
Stacktrace:
 [1] macro expansion
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:635 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:565
fuzzing: Test Failed at /home/brianc/projects/julia-dev/NNlib.jl/test/conv.jl:635
  Expression: dw_direct ≈ dw_im2col
   Evaluated: [0.18744640672662355] ≈ [0.022131711476828686]
Stacktrace:
 [1] macro expansion
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:635 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:565
fuzzing: Test Failed at /home/brianc/projects/julia-dev/NNlib.jl/test/conv.jl:635
  Expression: dw_direct ≈ dw_im2col
   Evaluated: [0.18744640672662355] ≈ [0.17519710699882415]
Stacktrace:
 [1] macro expansion
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:635 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:565
fuzzing: Test Failed at /home/brianc/projects/julia-dev/NNlib.jl/test/conv.jl:635
  Expression: dw_direct ≈ dw_im2col
   Evaluated: [0.18744640672662355] ≈ [0.16531469524979486]
Stacktrace:
 [1] macro expansion
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:635 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/projects/julia-dev/NNlib.jl/test/conv.jl:565
... etc.
``` 
AFAICT, multithreaded CI has been consistently (but not always) failing since https://github.com/FluxML/NNlib.jl/pull/242. That PR introduced `gradcheck` tests in the first place, so it's likely that the direct and im2col implementations had diverged for some time beforehand. It appears https://github.com/FluxML/NNlib.jl/pull/235 fixed some major issues with the latter, but evidently that was not enough to ensure consistent behaviour.

**Comment by ToucheSir** [comment]
Ok, a couple more interesting observations for the folks who actually understand these routines (i.e. not me) to work with.

1. Fuzzing fails with 1 Julia runtime thread and 1 BLAS thread set. So unless the GEMM implementations in NNlib are somehow ignoring that configuration, this appears to be an algorithmic issue.
2. Not all fuzz tests fail. I haven't combed through the whole set (still running them), but I have yet to see https://github.com/FluxML/NNlib.jl/blob/master/test/conv.jl#L633-L635 or https://github.com/FluxML/NNlib.jl/blob/master/test/conv.jl#L640-L642 fail.
3.  Not all test configurations fail, either. Since one `.` is printed for every iteration of https://github.com/FluxML/NNlib.jl/blob/master/test/conv.jl#L583-L587, searching over https://github.com/FluxML/NNlib.jl/blob/master/test/conv.jl#L597-L599 is probably not required.

**Comment by ToucheSir** [comment]
@staticfloat would you have any insight into why this might be happening? I have basically zero understanding of how the im2col implementation works, unfortunately.

**Comment by staticfloat** [comment]
@ToucheSir, thanks for the detailed info, I think I found the error: https://github.com/FluxML/NNlib.jl/pull/367

**Comment by CarloLucibello** [comment]
Does someone understand the buildkite error we are having? 
https://buildkite.com/julialang/nnlib-dot-jl/builds/306#2ff2a604-e66e-4ffc-99d4-abfc5e20be32/559-675

**Comment by staticfloat** [comment]
My first guess is that it might be a bug due to the `/` in my branch name.

**Comment by ToucheSir** [comment]
Interestingly, BuildKite was perfectly happy on the PR, but failed on https://github.com/FluxML/NNlib.jl/blob/2436b32cee107733343e411bb0fb52a1c0666e97/test/conv.jl#L739 after merging: https://buildkite.com/julialang/nnlib-dot-jl/builds/309#8c0bd06b-f65d-40d6-bb1a-7a70bd1600f3/245-444.

Coincidentally, this is the second instance in under a week of BuildKite being happy on a PR but not during/after integration. Granted the [other instance](https://github.com/FluxML/Flux.jl/pull/1797#issuecomment-984888582) was with a different layer and on a GPU path, so there may be no link whatsoever.

**Comment by ToucheSir** [comment]
After spending some time (unsuccessfully) trying to make sense of https://github.com/FluxML/Flux.jl/issues/1804, I wonder if these two issues are related. The common factor is the `∇(depthwise)conv_*` methods, which by default dispatch to im2col instead of direct implementations. `ConvTranspose`'s [forward pass](https://github.com/FluxML/Flux.jl/blob/master/src/layers/conv.jl#L283) calls `∇conv_data`, for example.

As a side note, not being able to repro these issues reliably/at all outside of Buildkite runs is a huge pain :disappointed:. The only changed variables I can think of compared to my local machines are Zen 2 vs Skylake/Haswell and 12c/24t vs 4c/8t, but alas both require a whole new set of hardware...
