### ISSUE TITLE
`rrule(::typeof(∇conv_filter)`

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/NNlib.jl#362]
We already have one for `∇conv_data` (https://github.com/FluxML/NNlib.jl/blob/master/src/conv.jl#L321). This would allow the lion's share of models to be twice-differentiable, e.g. https://discourse.julialang.org/t/how-to-add-norm-of-gradient-to-a-loss-function/69873/11.

**Comment by mcabbott** [comment]
Also #119

**Comment by mschauer** [comment]
To rephrase, `rrule(::typeof(∇conv_filter)...` relates to like to `rrule(::typeof(∇conv_data)`, see https://github.com/FluxML/NNlib.jl/blob/master/src/conv.jl#L321 like `∇conv_filter` to `∇conv_data`, see
https://github.com/FluxML/NNlib.jl/blob/c0b4b8b6e969422ff4af18b473d02192b27c9cf4/src/conv.jl#L212

?

**Comment by mschauer** [comment]
Educated guess :
```
@eval function rrule(::typeof($∇conv_filter), x, ȳ, cdims; kw...)
        function $∇conv_filter_pullback(Δ)
            Δ = colmajor(Δ)
            return (
                NoTangent(),
                @thunk($∇conv_data(unthunk(Δ), ȳ, cdims, kw...)),
                @thunk($conv(x, unthunk(Δ), cdims, kw...)),
                NoTangent(),
            )
        end
        return $∇conv_filter(x, ȳ, cdims; kw...), $∇conv_filter_pullback
    end


```

**Comment by DhairyaLGandhi** [comment]
Relevant to #386

**Comment by ToucheSir** [comment]
@mschauer would you be comfortable trying that out with `gradtest`? If not I can toss a quick PR together this weekend for iterating on it.

**Comment by mschauer** [comment]
If what I wrote looks credible perhaps @vincentmolin wants to give it a try? Trying it with https://github.com/FluxML/NNlib.jl/blob/c0b4b8b6e969422ff4af18b473d02192b27c9cf4/test/test_utils.jl#L13?

**Comment by vincentmolin** [comment]
``gradtest`` passing after a slight modification, submitted a pr #387
