### ISSUE TITLE
@fix and fused broadcasts

### ISSUE THREAD

**Issue by gustafsson** [FluxML/NNlib.jl#37]
Continued from https://github.com/JuliaGPU/CuArrays.jl/issues/71

The issue
```
> x = CuArray([2.]);
> @fix x.*log.(x)
ERROR: Broadcast output type Any is not concrete
```

Using `CUDAnative.log` explicitly is fine:
```
> x.*CUDAnative.log.(x)
1-element CuArray{Float64,1}:
 1.38629
```

If I expand `@fix` I get
```
> @macroexpand @fix x.*log.(x)
quote 
    ##702 = (NNlib._cufunc)(log, (NNlib.cudata).((x,))...)
    x .* ##702.(x)
end
```
Which evaluates to
```
> f = CUDAnative.log;
> x.*f.(x)
ERROR: Broadcast output type Any is not concrete
```
But using only `f` works.
```
> f.(x)
1-element CuArray{Float64,1}:
 0.693147
```

It seems to me there is some issue with fused broadcasts and saving an intrinsic in a variable? Could we change the `@fix` macro to evaluate `(NNlib._cufunc)(log, (NNlib.cudata).((x,))...)` when running the macro, and return `:(x .* CUDAnative.log.(x))` instead?

**Comment by MikeInnes** [comment]
It works if `f` is explicitly bound, or in a const:

```julia
julia> let f = CUDAnative.log
         xs .* f.(xs)
       end
3-element CuArray{Float32,1}:
 0.0
 1.38629
 3.29584

julia> const f = CUDAnative.log

julia> xs .* f.(xs)
3-element CuArray{Float32,1}:
 0.0
 1.38629
 3.29584
```

My guess is that Julia is failing to specialise on the function due to a heuristic, but I'm not sure. Some interesting evidence:

```julia
julia> @fix xs .* log.(xs)
ERROR: Return type couldn't be inferred for broadcast. Func: #5, CuArray{Float32,1}, ()

julia> f() = @fix xs .* log.(xs)

julia> f()
5-element CuArray{Float32,1}:
 0.0
 1.38629
 3.29584
 5.54518
 8.04719
```

> Could we change the `@fix` macro to evaluate `(NNlib._cufunc)(log, (NNlib.cudata).((x,))...)` when running the macro

`@fix` has to handle cases like [this](https://github.com/FluxML/Flux.jl/blob/d12fb98f2a1530a0c5ff46822c7d16c027d99d9c/src/layers/basic.jl#L78) where sigma may be dynamically bound to `log`, `tanh` etc. In theory, that should still all happen at compile time of course.

**Comment by MikeInnes** [comment]
Apparently [this](https://github.com/FluxML/Flux.jl/commit/8f73dc6e148eedd11463571a0a8215fd87e7e05b) is enough to fix it. Not totally sure why that is, but at least it works now.

**Comment by gustafsson** [comment]
Huh, that was interesting.

```
julia> using NNlib,CuArrays
julia> x = CuArray([2.f0])
julia> (function f() NNlib.@fix x.*log.(x) end)() # ok
julia> (assignmentform() = NNlib.@fix x.*log.(x))() # ok
julia> (function fr() return NNlib.@fix x.*log.(x) end)() # ... Any is not concrete
julia> (function() y = NNlib.@fix x.*log.(x); y end)() # ... Any is not concrete
```

Looking at the output of `@code_lowered` it seems to use `apply_type` when `@fix` succeeds (and not use a `Core.Box`):
```
julia> @code_lowered f()
CodeInfo(:(begin 
        nothing
        661 = (Core._apply)(NNlib._cufunc, (Core.tuple)(Main.log), (Base.broadcast)(NNlib.cudata, (Core.tuple)(Main.x)))
        #1 = $(Expr(:new, :((Core.apply_type)(Main.##1#2, (Core.typeof)(661))), :(661)))
        SSAValue(0) = #1
        return (Base.broadcast)(SSAValue(0), Main.x)
    end))

julia> @code_lowered fr()
CodeInfo(:(begin 
        nothing
        683 = (Core.Box)()
        SSAValue(0) = (Core._apply)(NNlib._cufunc, (Core.tuple)(Main.log), (Base.broadcast)(NNlib.cudata, (Core.tuple)(Main.x)))
        (Core.setfield!)(683, :contents, SSAValue(0))
        #5 = $(Expr(:new, :(Main.##5#6), :(683)))
        SSAValue(1) = #5
        return (Base.broadcast)(SSAValue(1), Main.x)
    end))
```

**Comment by gustafsson** [comment]
You're right!

I tried to wrap the assignments in a `let` and now I get the same `@code_lowered` from both `f` and `fr`.

**Comment by gustafsson** [comment]
Sure thing! https://github.com/FluxML/NNlib.jl/pull/38
