### ISSUE TITLE
Reverse CI

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/NNlib.jl#374]
Surprised this wasn't a thing already.

**Comment by mcabbott** [comment]
Can be copied from https://github.com/FluxML/Zygote.jl/pull/1033

What's the list? Flux, KNet, Avalon.

**Comment by ToucheSir** [comment]
That sounds like a good start. The list on https://juliahub.com/ui/Packages/NNlib/A7zdE/0.7.33?page=2 has a number of false positives (perhaps packages that used to depend on NNlib?), but I know that OptimalTransport definitely uses NNlib.
