### ISSUE TITLE
Fix non test related CI error

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/NNlib.jl#377]
https://buildkite.com/julialang/nnlib-dot-jl/builds/349#04a94b49-abff-4eb2-895a-869b73b4ffce/511-627

**Comment by darsnack** [comment]
Is it spurious? I feel like I have been seeing this consistently recently.

**Comment by ToucheSir** [comment]
I wanted to say that I only see it sometimes, but looking back it does seem to pop up regularly.
