### ISSUE TITLE
conv with SubArray

### ISSUE THREAD

**Issue by jbrea** [FluxML/NNlib.jl#39]
Is there are reason to force [x and w have the same type in conv](https://github.com/FluxML/NNlib.jl/blob/master/src/conv.jl#L27)? I would like to use conv with x being a view of another array, i.e. a SubArray. One solution could be to remove the type constraint for x on conv, conv!, ∇conv_filter!, conv2d!, conv2d_grad_w!, ∇conv_filter etc.

**Comment by MikeInnes** [comment]
Just historical accident as this was ported from C code. If you want to remove the restrictions and make sure things still work OK, you're more than welcome to.
