### ISSUE TITLE
NNlib 0.8.3 broke NNlibCUDA

### ISSUE THREAD

**Issue by maleadt** [FluxML/NNlib.jl#400]
A CI job that succeeded on Friday, using NNlib 0.8.2, now fails with the only seemingly relevant upgrade being NNlib 0.8.3:
- passed: https://buildkite.com/julialang/cuda-dot-jl/builds/2718#c98f56a2-5595-44af-b860-1d710ca3cb9e
- failing: https://buildkite.com/julialang/cuda-dot-jl/builds/2724#7b44ba38-2579-4bce-95f7-9cd970e20599

Errors include both a compilation failure, and failed tests.

**Comment by darsnack** [comment]
Xref https://github.com/FluxML/NNlib.jl/pull/399#issuecomment-1059886413

**Comment by mcabbott** [comment]
Sorry, my fault. I think I ignored the GPU tests in #392, as they were already failing for some other reason. #399 is the fix.

**Comment by maleadt** [comment]
Thanks. Normally I wouldn't mind, but we've added NNlibCUDA as reverse-CI to CUDA.jl, so it matters :-)

**Comment by mcabbott** [comment]
If someone approves #399 I can merge & tag right now.
