### ISSUE TITLE
NaN caused by `tanh_fast`

### ISSUE THREAD

**Issue by zhubonan** [FluxML/NNlib.jl#407]
FluxML/Flux.jl#1776 subsitutes `tanh` by `tanh_fast`, howeer, the latter gives `NaN` for large numbers:

I am on Julia 1.7.2 and Flux 0.13.

```julia
using Flux

julia> tanh_fast(1e10)
NaN

julia> tanh_fast(-1e10)
-1.0

julia> d = Dense(1=>1, tanh)
Dense(1 => 1, tanh)  # 2 parameters

julia> d([-1.e16])
1-element Vector{Float64}:
 NaN

julia> d([1.e16])
1-element Vector{Float64}:
 -1.0

```

`NaN` would then propagate down the network....

**Comment by mcabbott** [comment]
I think that's a stupid bug: There's a test which should use a constant for `x > sqrt(900)` to avoid this, but it uses `sign(y)` not `sign(x)`.

https://github.com/FluxML/NNlib.jl/blob/886b34c604192044380a2d73a2a1e07d09e19a38/src/activations.jl#L776-L784
