### ISSUE TITLE
Separable Convolutions

### ISSUE THREAD

**Issue by staticfloat** [FluxML/NNlib.jl#41]
Separable Convolutions (https://arxiv.org/abs/1610.02357) are really, really nice to have, and a must for fast/realtime image processing.  If nobody else does this, I will likely implement an im2col and view-based implementation of these later this summer, but I figured we should track this as they're rapidly becoming a mainstay in efficient (e.g. mobile) computer vision systems.

**Comment by jekbradbury** [comment]
I think that is currently WIP here https://github.com/FluxML/model-zoo/pull/41 and should perhaps be moved to NNlib?

**Comment by avik-pal** [comment]
The implementation in the pull request is quite slow and I am currently working on the im2col version of it. So I will try to get it done by this week possibly and send a PR as soon as possible if that is fine.

**Comment by datnamer** [comment]
Can this be closed per #42 ?

**Comment by MikeInnes** [comment]
Yup, would have thought so.
