### ISSUE TITLE
v0.8.6 contains breaking changes

### ISSUE THREAD

**Issue by lassepe** [FluxML/NNlib.jl#412]
The removal of `upsample_linear_wcn!`, `upsample_bilinear_whcn!` and `updample_trilinear_whdcn!`  as part of the patch release v0.8.6 broke NNlibCUDA. NNlibCUDA adds dispatches here:

- https://github.com/FluxML/NNlibCUDA.jl/blob/da73f077371a5f85660f6e7620099d74ddd11b6e/src/upsample.jl#L118
- https://github.com/FluxML/NNlibCUDA.jl/blob/da73f077371a5f85660f6e7620099d74ddd11b6e/src/upsample.jl#L240
- https://github.com/FluxML/NNlibCUDA.jl/blob/da73f077371a5f85660f6e7620099d74ddd11b6e/src/upsample.jl#L393

I guess those functions are not considered public API because they are not exported but the fact that another package from the same ecosystem extends them still makes this change kind of breaking.

**Comment by lassepe** [comment]
Note: I'm not sure whether this is considered an issue of NNlib or NNlibCUDA. One could also argue that  NNlibCUDA should not be allowed to add dispatches to an unexported function.

**Comment by VarLad** [comment]
Breaks Flux for me as well for some reason.

**Comment by avmnu-sng** [comment]
@VarLad  The reason is the `v0.8.6` release which breaks `NNlibCUDA` required to build `Flux`. Till we have a fix, you can  lock the `NNlib` version to `v0.8.5` to successfully build `Flux.`
```julia
Pkg.add([
    Pkg.PackageSpec(;name="Flux", version="0.13.3")
    Pkg.PackageSpec(;name="NNlib", version="0.8.5")
]);
```

**Comment by CarloLucibello** [comment]
Sorry for that, I was expecting a temporary breakage of NNlibCUDA but only when using `upsample` and not for general Flux users.

**Comment by CarloLucibello** [comment]
I'm tagging a new version of NNlibCUDA with a compact bound NNlib  <= 0.8.5, and then a new one with NNlib >= 0.8.6 when https://github.com/FluxML/NNlibCUDA.jl/pull/49 is merged

**Comment by cossio** [comment]
Why wasn't this caught by CI?

**Comment by lassepe** [comment]
Given that there are quite a few downstream packages, it may be a good idea moving forward to add some integration tests to catch these things before release. Maybe even just for Flux.

**Comment by CarloLucibello** [comment]
We do have integrations tests and they were failing indeed for https://github.com/FluxML/NNlib.jl/pull/410, I don't know how I didn't notice that, sorry for this mess

**Comment by CarloLucibello** [comment]
So V0.8.6 is no more and this can be closed due to https://github.com/JuliaRegistries/General/pull/61389
