### ISSUE TITLE
Activation functions have to be broadcasted by the user to act on arrays

### ISSUE THREAD

**Issue by theabhirath** [FluxML/NNlib.jl#422]
Right now, NNlib activations act on scalars, meaning that they have to be explicitly broadcasted by the user (`x -> relu.(x)`, for example) to act on arrays. This shows up as an anonymous function inside of Flux models, often making error messages cryptic and difficult to track down. One obvious solution is to simply add these methods in NNlib (I'm happy to volunteer), but I'm not sure if there's a reason this isn't done already?

**Comment by ToucheSir** [comment]
We've been hesitant to add an `Elementwise`/`Activation(f) = Base.Fix1(broadcast, f)` to Flux on the rationale that users can do it themselves, but given how many times this has popped up perhaps it is time to revisit that choice.

**Comment by darsnack** [comment]
I think a wrapper layer starts to veer too much towards a Flux DSL (we are taking about a function call after all).

Why isn't `relu(::AbstractArray)` etc. defined? That seems simplest. Alternatively, a method error hint would make things less cryptic. Though these solutions only apply to the activations in NNlib and not user defined activations.

**Comment by theabhirath** [comment]
I suppose we could include a note in the docs asking the users to define that dispatch as good practice?
