### ISSUE TITLE
Unstable performance

### ISSUE THREAD

**Issue by deahhh** [FluxML/NNlib.jl#461]
ENV:
(@v1.8) pkg> status
Status `~/.julia/environments/v1.8/Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.2
  [052768ef] CUDA v3.12.1
  [31a5f54b] Debugger v0.7.8
  [587475ba] Flux v0.13.11

CODE:
```Julia
using BenchmarkTools, CUDA, Flux
@benchmark NNlib.batched_mul(CUDA.rand(Float32, 1024, 9216, 8), CUDA.rand(Float32, 9216, 1024, 8))
```

OUTPUT:
BenchmarkTools.Trial: 161 samples with 1 evaluation.
 Range (min … max):   9.545 μs … 181.363 ms  ┊ GC (min … max): 0.00% … 0.61%
 Time  (median):     55.388 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   31.910 ms ±  63.999 ms  ┊ GC (mean ± σ):  1.12% ± 0.46%

  █                                                     ▁       
  █▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▇██▆▄▄▆ ▄
  9.54 μs       Histogram: log(frequency) by time       172 ms <

 Memory estimate: 800 bytes, allocs estimate: 25.

**Comment by chengchingwen** [comment]
The benchmark macro would measure the whole expression, which means you are measuring the gpu memory allocation overhead as well.
