### ISSUE TITLE
move issues from NNlibCUDA.jl

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/NNlib.jl#495]
After #492 is merged we should move here the issues from https://github.com/FluxML/NNlibCUDA.jl and update the README of that package with a deprecation message

**Comment by ToucheSir** [comment]
What's our story for Julia <1.9 then?

**Comment by CarloLucibello** [comment]
NNlibCUDA.jl can receive bugfix backports for Julia < 1.9

**Comment by ToucheSir** [comment]
In that case, we'd still need to have something in the tests here which either tests NNlibCUDA or the CUDA extension depending on Julia version.

This need for backports is what I was hoping to avoid by having the extension source also be a subpackage, BTW.

**Comment by CarloLucibello** [comment]
issues moved
