### ISSUE TITLE
Adding EnzymeRules

### ISSUE THREAD

**Issue by sethaxen** [FluxML/NNlib.jl#503]
### Motivation and description

On Slack, @ChrisRackauckas said that the functions defined in https://github.com/FluxML/NNlibCUDA.jl/tree/master/src/cudnn will need `EnzymeCore.EnzymeRules` overloads to work with Enzyme, since they use precompiled shipped binaries.

Or would it be better to provide overloads for functions defined in https://github.com/JuliaGPU/CUDA.jl/tree/master/lib/cudnn?

### Possible Implementation

This could be done on Julia v1.9 using an extension module and on pre-v1.9 the module could be loaded directly as described in https://pkgdocs.julialang.org/dev/creating-packages/#Transition-from-normal-dependency-to-extension, since EnzymeCore's sole dependency is Adapt, which is also a dependency here.

**Comment by wsmoses** [comment]
See https://github.com/FluxML/NNlib.jl/pull/536 for a conv example, adding these to the other layers would be incredibly valuable as well!

**Comment by wsmoses** [comment]
Given that the conv, scatter, gather, and other rules are presently in place, I propose that this issue be closed and new issues for any unsupported functions be added?
