### ISSUE TITLE
`NNlibCUDACUDNNExt` precompilation doesn't get finish

### ISSUE THREAD

**Issue by prbzrg** [FluxML/NNlib.jl#558]
In a fresh installation of Julia v1.10, `NNlibCUDACUDNNExt` precompilation doesn't get finish and shows `Waiting for background task / IO / timer. Interrupt to inspect` . It doesn't happen in github CI though.
how can I fix this problem?

```julia
Status `C:\Users\Hossein Pourbozorg\Code Projects\github-repos\ContinuousNormalizingFlows.jl\test\Project.toml`
  [47edcb42] ADTypes v0.2.6
  [c29ec348] AbstractDifferentiation v0.6.0
  [4c88cf16] Aqua v0.8.4
  [052768ef] CUDA v5.1.1
  [b0b7db55] ComponentArrays v0.15.7
  [ed09eef8] ComputationalResources v0.3.2
  [a93c6f00] DataFrames v1.6.1
  [31c24e10] Distributions v0.25.104
  [f6369f11] ForwardDiff v0.10.36
  [c3a54625] JET v0.8.22
  [b2108857] Lux v0.5.13
  [d0bbae9a] LuxCUDA v0.3.1
  [a7f614a8] MLJBase v1.0.1
  [37e2e3b7] ReverseDiff v1.15.1
  [0bca4576] SciMLBase v2.15.2
  [781d530d] TruncatedStacktraces v1.4.0
  [e88e6eb3] Zygote v0.6.68
  [02a925ec] cuDNN v1.2.1
  [56ddb016] Logging
  [8dfed614] Test
```
```julia
Julia Version 1.10.0
Commit 3120989f39 (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 18 on 12 virtual cores
```

**Comment by ToucheSir** [comment]
Can you try replicating this in a fresh environment with only NNlib, CUDA and cuDNN? It's possible a package which messes around with internals like JET or TruncatedStacktraces (which you should no longer need on 1.10) is causing issues with precompilation.

**Comment by prbzrg** [comment]
It's same with:
```julia
Status `C:\Users\Hossein Pourbozorg\Code Projects\S-Mine\Bug-Report\br-1\Project.toml`
  [052768ef] CUDA v5.1.1
  [b2108857] Lux v0.5.13
  [d0bbae9a] LuxCUDA v0.3.1
  [02a925ec] cuDNN v1.2.1
```

**Comment by ToucheSir** [comment]
That's not "only NNlib, CUDA and cuDNN" :). If precompilation succeeds with NNlib but fails when you add Lux, then that's an issue for them.

**Comment by prbzrg** [comment]
I tested with
```julia
Status `C:\Users\Hossein Pourbozorg\Code Projects\S-Mine\Bug-Report\br-1\Project.toml`
  [052768ef] CUDA v5.1.1
  [872c559c] NNlib v0.9.10
  [02a925ec] cuDNN v1.2.1
```
It's the same. And after Ctrl-C, I get many:
```julia
  1 dependency had output during precompilation:
┌ NNlib → NNlibCUDACUDNNExt
│  [pid 23744] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   async              000001f6b57f7240->000001f6ae61aa70
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 23744] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   async              000001f6b57f7240->000001f6ae61aa70
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 23744] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   async              000001f6b57f7240->000001f6ae61aa70
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└
```

**Comment by prbzrg** [comment]
I found it out, `julia --debug-info=2` makes it happen.

**Comment by ToucheSir** [comment]
I know the CUDA.jl docs touch briefly on debug flags, but this is unexpected. Does everything precompile if you remove NNlib?

**Comment by prbzrg** [comment]
`NNlib` precompiles, the only thing that doesn't precompile is `NNlibCUDACUDNNExt`.

**Comment by ToucheSir** [comment]
Did you interrupt the first `precompile` line? If not, looks like it completed successfully. I don't think any code in this repo would be responsible for the timers, so maybe something in CUDA or cuDNN?

**Comment by prbzrg** [comment]
Yes, If I don't interrupt it, it never stops.
If I ignore it, I can't use `NNlib`, each 15 second, a new prompt get generated:
```julia
julia> using CUDA, cuDNN

julia> using NNlib
Precompiling NNlibCUDACUDNNExt
        Info Given NNlibCUDACUDNNExt was explicitly requested, output will be shown live

[pid 28444] waiting for IO to finish:
 Handle type        uv_handle_t->data
 async              000001a17e3fb330->000001a176c92d70
This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.

[pid 28444] waiting for IO to finish:
 Handle type        uv_handle_t->data
 async              000001a17e3fb330->000001a176c92d70
This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.

[pid 28444] waiting for IO to finish:
 Handle type        uv_handle_t->data
 async              000001a17e3fb330->000001a176c92d70
This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.

[pid 28444] waiting for IO to finish:
 Handle type        uv_handle_t->data
 async              000001a17e3fb330->000001a176c92d70
This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
  Progress [>                                        ]  0/1
  ◓ NNlib → NNlibCUDACUDNNExt Waiting for background task / IO / timer. Interrupt to inspect
```

**Comment by ToucheSir** [comment]
I wonder if it could be waiting for CUDA.jl to download JLLs or something? People have found that to be very slow (>1hr) before. I tried to replicate this and was initially successful, but then couldn't re-repro it. There's likely some weird interaction with the compilation cache or something else Pkg-related going on. As such, I'd recommend escalating this to the usual CUDA.jl or Pkg.jl help channels.

**Comment by prbzrg** [comment]
Before reporting this issue, I used ```test CUDA``` to be sure all needed downloads are fulfilled. And the fact that it only happens when Julia has `--debug-info=2` in its arguments is evident to know the problem is not related to a missing download. Also during precompilation, there isn't any related network activity.
![Screenshot 2024-01-06 221627](https://github.com/FluxML/NNlib.jl/assets/79970151/10b4ee20-3e56-4ffd-bfe5-a7e539904be0)

**Comment by ToucheSir** [comment]
Ah right sorry, I'd forgotten about that flag. It may be that not much precompile testing has happened with it set.

**Comment by prbzrg** [comment]
On your system, does `]add CUDA, cuDNN, NNlib` precompile when you run Julia with `--debug-info=2`?

**Comment by ToucheSir** [comment]
I haven't tested and even if I could right now, I wouldn't capture much more info than you. I'd recommend escalating this ASAP since it appears to be an issue bigger than just NNlib.

**Comment by maleadt** [comment]
See https://docs.julialang.org/en/v1/devdocs/precompile_hang/ for how to debug this. I'm not sure what the source of `async` uv handles is though; @vtjnash?

In any case, I wouldn't immediately suspect CUDA.jl here, as `-g2` only affects its runtime code generation, which shouldn't be done globally / during precompilation anyway (as it breaks the ability to precompile packages on systems without CUDA).

**Comment by prbzrg** [comment]
I followed it and reach to:
```julia
julia> Aqua.test_persistent_tasks(cuDNN)
Test Failed at C:\Users\Hossein Pourbozorg\.julia\packages\Aqua\9p8ck\src\persistent_tasks.jl:29
  Expression: !(has_persistent_tasks(package; kwargs...))

ERROR: There was an error during testing

```

**Comment by maleadt** [comment]
Thanks, that narrows it down! It's a bug in the cuDNN initializer; I'll push a fix.

**Comment by maleadt** [comment]
cuDNN 1.2.2 should fix this: https://github.com/JuliaRegistries/General/pull/98436

**Comment by prbzrg** [comment]
The issue is resolved now. Thank you for fixing it.
