### ISSUE TITLE
`conv_bias_act!` allocates for activation in CUDNN

### ISSUE THREAD

**Issue by avik-pal** [FluxML/NNlib.jl#575]
https://github.com/FluxML/NNlib.jl/blob/d85402aa39ddc6386d194e0dad88ab2e514ec5ea/ext/NNlibCUDACUDNNExt/conv.jl#L131-L133

in the cudnn implementation it creates a new array instead of overwriting `y` while for the generic implementation https://github.com/FluxML/NNlib.jl/blob/d85402aa39ddc6386d194e0dad88ab2e514ec5ea/src/conv_bias_act.jl#L10-L12 we don't reallocate. We should probably be consistent in whichever behavior we choose (my personal preference would be to never reallocate)

**Comment by ToucheSir** [comment]
The allocating version appears to go back to an ancient version of CUDA.jl. It should be an easy change to make it in-place.

**Comment by avik-pal** [comment]
Just wanted to confirm that it wasn't intentional.
