### ISSUE TITLE
Updating `Documenter.jl` to a more recent version?

### ISSUE THREAD

**Issue by dom-linkevicius** [FluxML/NNlib.jl#577]
### Motivation and description

Hi,

I'm documenting a package via `Documenter.jl` and want to refer to a few functions in `NNlib.jl` via `@extref`. However, because `Documenter.jl` in `NNlib.jl` is fixed to 0.27, it does not generate an inventory file and this causes issues in using `@extref`. Is there any particular reason why `Documenter.jl` is fixed to 0.27?

### Possible Implementation

I've a local branch of `NNlib.jl` where I've updated the `Documenter.jl` version, commented out one missing docstring (`∇upsample_nearest`) that makes the doc build error and have a working solution. If this is of interest, I can open a PR.

**Comment by mcabbott** [comment]
Sounds great, I presume nobody got around to updating it.

**Comment by CarloLucibello** [comment]
closed in #578
