### ISSUE TITLE
Integration with Batched.jl

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/NNlib.jl#76]
Discussed with @MikeInnes on slack a little bit. I implemented some batched operations and its dependent types here: https://github.com/Roger-luo/Batched.jl

Since we can overload operators for `BatchedArray`, this won't need any extra code for the AD (as long as you input your data/define the variable as a `BatchedArray`). So I was thinking to directly add a dependency in `Flux`.

Or what is preferred to have in NNlib?

PS. Currently, the `batched_gemm` in `Batched` is 2x faster than PyTorch, `batched_tr` is 363x faster for a naive python loop with `torch.trace` in PyTorch (they don't have batched trace....)

cc: @MikeInnes

**Comment by MikeInnes** [comment]
It would be great to have the `batched_gemm` kernel in NNlib. Just having the kernel itself works well since we can then add AD and GPU support separately, and then Batched.jl will work well with Flux and CuArrays out of the box.

**Comment by Roger-luo** [comment]
You mean let Batched depends on NNlib?

I was actually trying to have kernels in Batched.jl or some separate package (so the Array types are actually separated), this will allow me to prototyping things faster, because in principle all the operations in BLAS and LAPACK (or operations on `AbstractArray`) can be batched with similar method, which will looks like a special broadcast: only broadcast across batch dimensions.

And regarding to AD, there is no need to add special AD pass for batched operations, because the operator can be overloaded for batched types. You can use them as if using normal operations.

**Comment by MikeInnes** [comment]
Does Batched have GPU implementations now? I see them on the readme but not in the code. I'm thinking about whether we should just have CuArrays depend on Batched and add GPU implementations there.

I also wonder if it should be called `BatchedMatrices` or something similar, since it's quite specific to that and might otherwise give the impression of doing more general batching of data structures.

**Comment by Roger-luo** [comment]
Yes, the `BatchedArray`s are just a wrapper around other arrays. So it doesn't matter whether it is `CuArray` or `Array` inside, it will dispatch the `mul` to corresponding `batched_gemm` routines. I ported `gemmStridedBatched` from CUBLAS in CuArrays a few months ago, and some other batched routines like `batched_tr` is in `BatchedRoutines.jl`.

> whether we should just have CuArrays depend on Batched and add GPU implementations there.

Batched depends on `BatchedRoutines.jl` and `BatchedRoutines` depends on `CuArrays` when CUDA is available. (I wrote a hacky build script to update the Project.toml when CUDA is available, since there's no conditional dependencies support in Pkg for now)

But the problem is that I think `Batched.jl` itself is not ready to be a stable dependency now. I had some refactoring and re-think on this package after this issue last year, it probably need some re-design to make it more like a group of arrays, it miss a lot array functions at the moment, since I only implemented a few. (and maybe need to be renamed to `BatchedArrays.jl`)

> I also wonder if it should be called BatchedMatrices or something similar, since it's quite specific to that and might otherwise give the impression of doing more general batching of data structures.

I think batched structure is not only useful for matrices or vectors, it might be rare, but it can be useful for rank-3 tensors when you contract something called PEPS (Projected Entangled Pair States). So I would like to make it more general, and only assumes the last dimension to be the batched dimension (or maybe last a few dimension to be batch dimension).

I will re-touch this package a bit later in June. but anyone want to work on this together is welcome.

**Comment by MikeInnes** [comment]
Ok, for now we can just merge the basic routines into NNlib and add CUDA support from there then.

**Comment by Roger-luo** [comment]
Yes, I think that's a simpler solution, and we could always move things to a single package later. I could also help to port some routines for now.

**Comment by CarloLucibello** [comment]
we have batched_mul now
