### ISSUE TITLE
Overflow of Float64 logistic sigmoid derivative

### ISSUE THREAD

**Issue by ornithos** [FluxML/NNlib.jl#78]
I've encountered NaN derivatives when using the logistic sigmoid (σ) for moderate sized negative numbers. I think the boundary is about x=-709.783:

```julia
using Flux: Tracker
using ForwardDiff, NNlib

# Within Flux
x = Tracker.param(-709.783)
Tracker.back!(σ(x))
Tracker.grad(x) # = NaN

# Overflow in Dual Number:
σ(ForwardDiff.Dual(-709.783,1.0))  # Dual{Nothing}(0.0,NaN)
```

since (1 + exp(709.782)) ≈ 1.8 x 10^308. Given that there is a σ_stable function [defined](https://github.com/FluxML/NNlib.jl/blob/20aa7005c2ad2e511b4332a8af7920a2bac7a067/src/activation.jl#L12) presumably for precisely this issue when using Float32, should this be extended to all real numbers?

EDIT: A similar problem occurs in `softplus` at the same (negated) value, which may benefit from setting to the identity above e.g. x=80. (The other activation functions look ok.)

**Comment by MikeInnes** [comment]
Yeah, happy to take patches here. We could do something like `ifelse(x < lower_bound(x), ...` where `lower_bound` dispatches on type.

**Comment by MJ10** [comment]
So essentially there is just one definition
```julia
σ(x) = ifelse(x < lower_bound(x),  zero(x), one(x) / (one(x) + exp(-x)))
```
and we have define lower_bound as
```julia
lower_bound(x::Float32) = ...
lower_bound(x::Float64) = ...
...
```
Is this right or did you mean something else? @MikeInnes

**Comment by MikeInnes** [comment]
Yeah that seems right to me.

**Comment by MJ10** [comment]
```julia
σ(x) = ifelse(x < lower_bound(x), zero(x), one(x) / (one(x) + exp(-x)))

lower_bound(x::Float32) = -80
lower_bound(x::Float64) = -709
```
So this can replace the separate definitions for stable right? I'm not sure how to include the `Flux.Tracker.TrackerReal` types without requiring the package like `ForwardDiff`.

**Comment by MikeInnes** [comment]
Yes, it can replace `σ_stable`. I would probably just do it for `Dual` types for now, since those are used by Flux's broadcast anyway. The fallback should be `typemin`.

**Comment by MJ10** [comment]
```
ERROR: MethodError: no method matching lower_bound(::Flux.Tracker.TrackedReal{Float64})
```
I'm getting this error on defining for just `Float32`, `Float64`, `ForwardDiff.Dual{T,Float32}` and `ForwardDiff.Dual{T,Float64}`. Which is why I was wondering if I should define it separately for `Flux.Tracker.TrackedReal`

**Comment by MJ10** [comment]
@MikeInnes any help with this?

**Comment by MikeInnes** [comment]
It should work if you broadcast over a tracked array rather than a single tracked real. You can fix by defining a fallback for `lower_bound` that returns `typemin(x)` (that won't fix the original issue but it'll work when broadcasted, which will have to do for now).

**Comment by cossio** [comment]
I think a better definition of `sigmoid` goes like:

```julia
function sigmoid(x)
    t = exp(-abs(x))
    s = inv(one(t) + t)
    x ≥ 0 ? s : t * s
end
```

**Comment by cossio** [comment]
I made a PR, https://github.com/FluxML/NNlib.jl/pull/198
