### ISSUE TITLE
The slicing in the inner loops in the pooling layers are expensive

### ISSUE THREAD

**Issue by KristofferC** [FluxML/NNlib.jl#87]
Ref https://gist.github.com/KristofferC/34178cf812f2b3ea468ca217a103c4a6

Removing the slicing (and adding an `@inbounds`) gives a 30x speedup for the maxpooling.

**Comment by MikeInnes** [comment]
Neat. Sounds worth a PR?

**Comment by KristofferC** [comment]
Yep, will do.
