### ISSUE TITLE
Use of pointer based gemm! is unsafe

### ISSUE THREAD

**Issue by andreasnoack** [FluxML/NNlib.jl#96]
Ideally, it wouldn't be necessary to pass pointers around as in https://github.com/FluxML/NNlib.jl/blob/d07ac0bfd3c71c3a29bc9c22becbba19227bbeb5/src/impl/conv.jl#L280. It would be good to test how much slower a version based on views would be. If it is too costly then it would be best to add some `GC.@preserve`s since, I believe, the current version is an inlining away from segfaulting.

**Comment by KristofferC** [comment]
Even without inlining, the `pointer(x2, ...)` could be invalid at any time.
